name: Release
on:
    push:
        tags:
            - 'v*'
    workflow_dispatch:

jobs:
    release:
        strategy:
            fail-fast: false
            matrix:
                platform: [macos-latest, ubuntu-20.04, windows-latest]
        runs-on: ${{ matrix.platform }}
        env:
            TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: 'Build Changelog'
              id: build_changelog
              uses: mikepenz/release-changelog-builder-action@v3
              with:
                  commitMode: true
                  configurationJson: |
                      { "categories": [
                              {
                                  "title": "## 📦 Uncategorized",
                                  "labels": []
                              }
                          ],
                          "template": "#{{CHANGELOG}}\n\nUncategorized:\n#{{UNCATEGORIZED}}\n\nIgnored:\n#{{IGNORED}}\n\n#{{UNCATEGORIZED_COUNT}}\n#{{IGNORED_COUNT}}",
                          "pr_template": "- #{{TITLE}}\n",
                          "empty_template": "#{{OWNER}}\n#{{REPO}}\n#{{FROM_TAG}}\n#{{TO_TAG}}",
                          "max_pull_requests": 1000,
                          "max_back_track_time_days": 1000
                      }

            - name: Install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-20.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

            - name: Rust setup
              uses: dtolnay/rust-toolchain@stable

            - name: Rust cache
              uses: swatinem/rust-cache@v2
              with:
                  workspaces: './src-tauri -> target'

            - name: Sync node version and setup cache
              uses: actions/setup-node@v3
              with:
                  node-version: 'lts/*'
                  cache: 'npm'

            - name: Install app dependencies and build web
              run: npm i && npm run build

            - name: Build the app
              uses: tauri-apps/tauri-action@dev

              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

              with:
                  tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
                  releaseName: 'Kimaier v__VERSION__' # tauri-action replaces \_\_VERSION\_\_ with the app version.
                  releaseBody: |
                      ${{ steps.build_changelog.outputs.changelog }}

                      See the assets to download this version.
                  releaseDraft: true
                  prerelease: false
